const obj1 = { a: 1, b: 2 };
const obj2 = { b: 3, c: 4 };

const mergedObject = {
    ...obj1,
    ...obj2
};

// IL VALORE DI B DI OBJ2 SI SOVRASCRIVE AUTOMATICAMENTE AL VALORE 
// DI B DI OBJ1 PERCHE' ABBIAMO INSERITO OBJ2 DOPO DI OBJ1 NELL'OGGETTO MERGEDOBJECT
// SE L'AVESSIMO MESSO PRIMA AVREMMO DOVUTO RIDICHIARARE UNA KEY DI
// MERGEDOBJECT DI NOME B E DARGLI COME VALORE 3

