const originalArray = [1, 2, 3, 4, 5];

const cloneArray = [...originalArray];

// COSI FACENDO SE VADO A MODIFICARE ORIGINALARRAY NON MODIFICO ANCHE CLONEARRAY
// PERCHE'CLONE ARRAY NON PRENDE IN RIFERIMENTO LO SPAZIO IN MEMORIA DI ORIGINALARRAY
// MA E' UN ARRAY A PARTE CON DENTRO GLI ELEMENTI CHE HA ORIGINALARRAY FINO ALLA RIGA 3
